- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Amber
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  - Train
  - FlandHighPop
  - OasisHighPop
  - Barratry
  - Kettle
  - Submarine
  - Delta
  - Leonid # by GoobStation for GoobStation
  - Elkridge # ShibaStation - Elkridge
